# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SERVER_IP }}
      - name: SSH into Google Cloud Console
        run: ssh -o StrictHostKeyChecking=no kgasasira69@${{ secrets.SERVER_IP }} 'bash -s' < ./.github/workflows/update_server.sh
